CREATE TABLE books(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,

    CONSTRAINT chk_books_title
        CHECK (length(trim(title)) > 0),

    CONSTRAINT chk_books_author
        CHECK (length(trim(author)) > 0),

    CONSTRAINT chk_books_price
        CHECK (price >= 0),

    CONSTRAINT chk_books_currency
        CHECK (currency = 'EUR')
)