CREATE TABLE app_users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,

    CONSTRAINT uk_app_users_email UNIQUE (email),

    CONSTRAINT chk_app_users_email_normalized
        CHECK (
            email = lower(email)
                AND email = trim(email)
                AND length(email) > 0
            )
);