CREATE TABLE cart_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT  NOT NULL REFERENCES app_users (id),
    book_id  BIGINT  NOT NULL REFERENCES books (id),
    quantity INTEGER NOT NULL CHECK (quantity BETWEEN 1 AND 99),
    CONSTRAINT uk_cart_user_book UNIQUE (user_id, book_id)
);

CREATE TABLE customer_orders
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT                   NOT NULL REFERENCES app_users (id),
    idempotency_key UUID                     NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    total           NUMERIC(18, 2)           NOT NULL CHECK (total >= 0),
    currency        VARCHAR(3)               NOT NULL CHECK (currency = 'EUR'),
    CONSTRAINT uk_order_user_key UNIQUE (user_id, idempotency_key)
);

CREATE TABLE order_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT         NOT NULL REFERENCES customer_orders (id),
    book_id    BIGINT         NOT NULL,
    title      VARCHAR(255)   NOT NULL,
    author     VARCHAR(255)   NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    quantity   INTEGER        NOT NULL CHECK (quantity BETWEEN 1 AND 99),
    CONSTRAINT uk_order_book UNIQUE (order_id, book_id)
);

-- book_id in order_items is a historical identifier, not a catalog relationship.
-- Title, author and unit_price remain available after future catalog changes.